### ISSUE TITLE
Folder name suggestion: `config`

### ISSUE THREAD

**Issue by nainemom** [pi0/config-dir#1]
As you know most of unix based distros considers files or folders starting with `.` as a hidden file. And in terms of value, I think this folder is more valuable than for example `node_modules` or package manager `lock` file to be displayed by default.
So why not just be the `config` instead of `.config`?

**Comment by KubaJastrz** [comment]
Probably because of XDG.

Also, https://github.com/cosmiconfig/cosmiconfig supports `.config` too.

**Comment by Jak2k** [comment]
.config has the advantage of being at the top of the file explorer in VS-Code.

**Comment by pi0** [comment]
Thanks for the suggestion. Yes i agree it might make it harder for File Explorer tools to see this config meanwhile it has advantage of being sorted as first directory and it is not usually hidden in code editors. PS: Consider many of current top-level files are prefixed with dot already so it is not a new issue.

Regardless I have mentioned your idea in the alternatives section: https://github.com/pi0/config-dir/blob/main/README.md#alternative-directory-names

**Comment by pi0** [comment]
Let's followup from https://github.com/pi0/config-dir/discussions/3

**Comment by pawamoy** [comment]
Honestly, having it shown earlier, but amongst many other dot-directories doesn't really make a difference.

![config](https://github.com/pi0/config-dir/assets/3999221/2350a4a4-e8bc-423f-a76f-acb093f59bc7)

As said in #13, I'd find it weird to put my config files directory in the "hidden, ignored" group, next to cache and build artifacts directories.

I suppose we can tolerate `.github` because it starts with `.git` :shrug:
